site_name: KSM Lernfeld 13

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown
  - search

extra_css:
  - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_KSM_LF13

site_url: https://herr-nm.github.io/MMBbS_KSM_LF13/

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - Fallbeispiel Steuerbüro: 'fallbeispiel_steuerbuero.md'